<?php
/**
 * @file
 * Code for the Open Atrium Subgroup Intergration for Spaces feature.
 */

include_once 'oa_subspaces.features.inc';

/**
 * Name of default Parent Space field.
 */
define('OA_PARENT_SPACE', 'oa_parent_space');
/**
 * Name of caches.
 */
define('OA_SUBSPACES_CACHE_CHILDREN', 'oa_subspaces_children');
define('OA_SUBSPACES_CACHE_PARENTS', 'oa_subspaces_parents');

/**
 * Implements hook_form_alter().
 * Hook into the Node Edit form
 */
function oa_subspaces_form_node_form_alter(&$form, $form_state, $form_id) {
  $node = $form['#node'];

  if (isset($form[OA_PARENT_SPACE][LANGUAGE_NONE][0])) {
    $form['#validate'][] = 'oa_subspaces_form_node_form_validate';

    // make some shortcut pointers to make the rest of this code easier to read
    $parent_default = &$form[OA_PARENT_SPACE][LANGUAGE_NONE][0]['default'];
    $parent_admin   = &$form[OA_PARENT_SPACE][LANGUAGE_NONE][0]['admin'];

    // clean up the edit form
    if (!empty($parent_admin['#options'])) {
      $all = array();
      foreach ($parent_default['#options'] + $parent_admin['#options'] as $op => $value) {
        if (is_array($value)) {
          foreach($value as $id => $title) {
            $all[$id] = $title . ' ' . '[' . drupal_strtolower($op) . ']';
          }
        }
        else {
          $all[$op] = $value;
        }
      }
      $parent_default['#options'] = $all;
//    don't unset the 'admin' field, just hide it for simplicity.
//    need value to persist in form
      $parent_admin['#access'] = FALSE;
    }
    $parent_default['#title'] = t('Parents');
    $parent_default['#description'] = t('Inherit membership from the selected parents.');
    $type = $form['#node']->type;
    $gid = oa_core_get_space_context();
    $admin_access = user_access('administer group') || ($gid == 0 ? node_access('create', $type) : og_user_access('node', $gid, "create $type content"));
    if (empty($form['#node']->nid)) {
      // If they are being granted create permission based on group permission
      // restrict the parent field to current group so don't have to deal with
      // changing values in form based on changed parent field.
      if (!$admin_access) {
        if (!$gid || !in_array($gid, array_keys($parent_default['#options']))) {
          drupal_access_denied();
          die();
        }
        else {
          $parent_default['#default_value'] = array($gid => $gid);
          $parent_default['#access'] = FALSE;
          drupal_set_title(t('Create @type in @title', array('@type' => node_type_get_name($type), '@title' => $parent_default['#options'][$gid])));
        }
      }
    }
    // When on edit form, restrict parent and space type field on edit
    // to avoid any access issues between space type and parent.
    elseif (!$admin_access && !empty($form['field_oa_space_type'])) {
      $form['field_oa_space_type']['#access'] = FALSE;
      $form[OA_PARENT_SPACE]['#access'] = FALSE;
    }

    // remove any children of this space from the selection list
    if (!empty($node->nid)) {
      $children = array();
      _oa_subspaces_get_children_groups('node', $node->nid, $children);
      foreach ($parent_default['#options'] as $key => $option) {
        if (($key == $node->nid) || (in_array($key, $children))) {
          unset($parent_default['#options'][$key]);
        }
      }
    }
    if (isset($form[OG_USER_INHERITANCE_FIELD][LANGUAGE_NONE]) && isset($form[OG_USER_INHERITANCE_PERMISSION_FIELD][LANGUAGE_NONE])) {
      $form[OG_USER_INHERITANCE_PERMISSION_FIELD][LANGUAGE_NONE]['#states'] = array(
        'visible' => array(
          ':input[name="og_user_inheritance[und]"]' => array('value' => 1),
        ),
      );
      // This field acts odd when required but user doesn't have access, throws
      // a required warning when 0 is valid and works fine otherwise
      $form[OG_USER_INHERITANCE_PERMISSION_FIELD][LANGUAGE_NONE]['#required'] = FALSE;
    }
  }

  // fill in any value specified in URL
  $parent = NULL;
  if (!empty($_GET[OA_PARENT_SPACE]) && is_numeric($_GET[OA_PARENT_SPACE])) {
    $parent = $_GET[OA_PARENT_SPACE];
  }
  if (!empty($parent_default['#options']) && empty($parent_default['#default_value']) && !empty($parent) && array_key_exists($parent, $parent_default['#options'])) {
    $parent_default['#default_value'] = $parent;
  }
}

/**
 * Validation function for node edit form
 */
function oa_subspaces_form_node_form_validate($form, &$form_state) {
  $node = $form['#node'];
  if (!empty($node->nid) && !empty($form_state['values'][OA_PARENT_SPACE][LANGUAGE_NONE])) {
    foreach ($form_state['values'][OA_PARENT_SPACE][LANGUAGE_NONE] as $oa_parent) {
      if (!empty($oa_parent['target_id']) && ($oa_parent['target_id'] == $node->nid)) {
        form_set_error(OA_PARENT_SPACE, t('You cannot set the Parent Space to itself.'));
        return;
      }
    }
  }
}

/**
 * Return children of Space, regardless of the inheritance field.
 *
 * @param $group_type
 *   The group (entity) type.
 * @param $group_id
 *   The group (entity) ID.
 *
 * @return array
 *   An array of NIDs.
 */
function oa_subspaces_get_children_groups($group_type, $group_id) {
  $cid = oa_core_get_cache_id(OA_SUBSPACES_CACHE_CHILDREN, $group_id, FALSE, array($group_type));

  $static_cache = &drupal_static(OA_SUBSPACES_CACHE_CHILDREN);
  if (isset($static_cache[$cid])) {
    return $static_cache[$cid];
  }

  if ($cache = cache_get($cid)) {
    $static_cache[$cid] = $cache->data;
    return $cache->data;
  }

  $children_groups = array();
  _oa_subspaces_get_children_groups($group_type, $group_id, $children_groups);

  // Cache the list of children.
  $static_cache[$cid] = $children_groups;
  cache_set($cid, $children_groups);

  return $children_groups;
}

/**
 * Helper function for oa_subspaces_get_children_groups().
 *
 * @see oa_subspaces_get_children_groups()
 */
function _oa_subspaces_get_children_groups($group_type, $group_id, &$children_groups) {
  $children = og_subgroups_get_associated_entities($group_type, $group_id);
  foreach ($children as $children_type => $children_ids) {
    foreach ($children_ids as $child_id) {
      if (!in_array($child_id, $children_groups)) { // prevent recursion
        $children_groups[] = $child_id;
        _oa_subspaces_get_children_groups($children_type, $child_id, $children_groups);
      }
    }
  }
}

/**
 * Return parents of a Space, regardless of the inheritance field.
 *
 * @param $group_type
 *   The group (entity) type.
 * @param $group_id
 *   The group (entity) ID.
 *
 * @return array
 *   An array of NIDs.
 */
function oa_subspaces_get_parent_groups($group_type, $group_id) {
  $cid = oa_core_get_cache_id(OA_SUBSPACES_CACHE_PARENTS, $group_id, FALSE, array($group_type));

  $static_cache = &drupal_static(OA_SUBSPACES_CACHE_PARENTS);
  if (isset($static_cache[$cid])) {
    return $static_cache[$cid];
  }

  if ($cache = cache_get($cid)) {
    $static_cache[$cid] = $cache->data;
    return $cache->data;
  }

  $result = array();
  $parents = og_subgroups_parents_load($group_type, $group_id, FALSE);
  if (!empty($parents[$group_type])) {
    $result = array_values($parents[$group_type]);
  }

  // Cache the list of parents.
  $static_cache[$cid] = $result;
  cache_set($cid, $result);

  return $result;
}

/**
 * Implements hook_oa_clear_cache
 */
function oa_subspaces_oa_clear_cache($node = NULL, $uid = NULL, $include_archived = FALSE) {
  $cid = oa_core_get_cache_id(OA_SUBSPACES_CACHE_CHILDREN, NULL, $include_archived);
  oa_core_clear_cache(OA_SUBSPACES_CACHE_CHILDREN, $cid);

  $cid = oa_core_get_cache_id(OA_SUBSPACES_CACHE_PARENTS, NULL, $include_archived);
  oa_core_clear_cache(OA_SUBSPACES_CACHE_PARENTS, $cid);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function oa_subspaces_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['og_group_ref_target_id']['#options'])) {
    $view = $form_state['view'];
    $exposed_form_overrides = $view->display_handler->get_option('exposed_form_overrides');
    $pane_conf = $view->display_handler->get_option('pane_conf');
    if ((!isset($exposed_form_overrides['filters']['og_group_ref_target_id']) ||
        (!empty($exposed_form_overrides['filters']['og_group_ref_target_id']))) &&
       (!isset($pane_conf['show_exposed_form']) || !empty($pane_conf['show_exposed_form']))) {
        // field is exposed to user so rearrange subspaces within spaces
      _oa_subspaces_rearrange_options($form['og_group_ref_target_id']['#options']);
    }
    $settings = _oa_subspaces_find_view_settings($form_state['view'], $form_state);
    if ($settings['og_group_ref_target_id'] && is_numeric($settings['og_group_ref_target_id'])) {
      _oa_subspaces_add_element_all($form, $form_state, $settings);
      _oa_subspaces_add_element_parent($form, $form_state, $settings);
    }
  }
}

/**
 * Converts a flat list of spaces into a hierarchical space/subspace list
 */
function _oa_subspaces_rearrange_options(&$options) {
  // Reorganize options for better usability.
  $nid_options = array_keys($options);
  $indexed = array();
  foreach ($options as $nid => $title) {
    $parents = oa_core_get_parents($nid);
    $indexed[$nid]['title'] = $title;
    $indexed[$nid]['parent'] = (empty($parents) || !in_array($parents[0], $nid_options)) ? 0 : $parents[0];
    $indexed[$nid]['children'] = array();
  }

  // convert flat list into hierarchy
  foreach ($indexed as $id => $row) {
    $indexed[$row['parent']]['children'][$id] =& $indexed[$id];
  }

  // add the nested -- to titles to convert back to flat
  if (!empty($indexed[0]['children'])) {
    $options = _oa_subspaces_build_options($indexed[0]['children']);
  }
}

/**
 * Helper to convert a hierarchical array back to a flat list with -- in titles
 */
function _oa_subspaces_build_options($list, $depth = 0) {
  $result = array();
  if (!empty($list)) {
    foreach ($list as $nid => $sublist) {
      $result[$nid] = str_repeat('--', $depth) . $sublist['title'];
      $result += _oa_subspaces_build_options($sublist['children'], $depth+1);
    }
  }
  return $result;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function oa_subspaces_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  // Doing it to the exposed form alone doesn't work :(.
  // Need to also do it for the pane config form
  if (!empty($form['exposed']['filter-og_group_ref_target_id']['og_group_ref_target_id'])) {
    $settings = _oa_subspaces_find_view_settings($form_state['view'], $form_state);
    _oa_subspaces_rearrange_options($form['exposed']['filter-og_group_ref_target_id']['og_group_ref_target_id']['#options']);
    _oa_subspaces_add_element_all($form['exposed']['filter-og_group_ref_target_id'], $form_state, $settings, array('exposed'));
    _oa_subspaces_add_element_parent($form['exposed']['filter-og_group_ref_target_id'], $form_state, $settings, array('exposed'));
  }
}

/**
 * Helper to add a checkbox to the exposed filter
 */
function _oa_subspaces_add_checkbox(&$element, $id, $title, &$form_state, $settings, $parents = array()) {
  $parents[] = $id;
  $value = $settings[$id];
  $element[$id] = array(
    '#title' => t($title),
    '#type' => 'checkbox',
    '#default_value' => $value,
    '#parents' => $parents,
  );
  // Unchecked checkboxes need to have a NULL input or else it is still
  // considered to be a checked box
  // see form.inc form_type_checkbox_value
  if (empty($value) && isset($form_state['input'][$id])) {
    unset($form_state['input'][$id]);
  }
}

/**
 * Helper to add the 'Show subspace content' checkbox at same place as group ref.
 */
function _oa_subspaces_add_element_all(&$element, &$form_state, $settings, $parents = array()) {
  _oa_subspaces_add_checkbox($element, 'og_subspaces_view_all', 'Show subspace content', $form_state, $settings, $parents);
}

/**
 * Helper to add the 'Show parent content' checkbox at same place as group ref.
 */
function _oa_subspaces_add_element_parent(&$element, &$form_state, $settings, $parents = array()) {
  _oa_subspaces_add_checkbox($element, 'og_subspaces_view_parent', 'Show parent content', $form_state, $settings, $parents);
}

/**
 * Finding the active current configuration for each is a pane in the ***.
 */
function _oa_subspaces_find_view_settings($view = NULL, $form_state = NULL) {
  $find = array('og_subspaces_view_all', 'og_subspaces_view_parent', 'oa_section_ref_target_id', 'og_group_ref_target_id', 'og_group_ref_target_id_mine');
  $return = array();
  foreach ($find as $key) {
    // check for a form key that always returns a value
    // otherwise checkboxes (like og_subspaces_view_all) cannot be unchecked
    // because they don't return any result in $_GET from browser
    if (isset($_GET['og_group_ref_target_id'])) {
      $return[$key] = isset($_GET[$key]) ? $_GET[$key] : NULL;
    }
    elseif (isset($_POST['exposed'][$key])) {
      $return[$key] = $_POST['exposed'][$key];
    }
    elseif ($form_state && isset($form_state['values']['exposed'][$key])) {
      $return[$key] = $form_state['values']['exposed'][$key];
    }
    elseif ($form_state && isset($form_state['values'][$key])) {
      $return[$key] = $form_state['values'][$key];
    }
    elseif ($form_state && isset($form_state['input'][$key])) {
      $return[$key] = $form_state['input'][$key];
    }
    elseif ($form_state && isset($form_state['conf']['exposed'][$key])) {
      $return[$key] = $form_state['conf']['exposed'][$key];
    }
    elseif ($view && isset($view->exposed_raw_input[$key])) {
      $return[$key] = $view->exposed_raw_input[$key];
    }
    elseif ($view && isset($view->exposed_input[$key])) {
      $return[$key] = $view->exposed_input[$key];
    }
    elseif ($view && isset($view->display_handler->options['pane_conf'][$key])) {
      $return[$key] = $view->display_handler->options['pane_conf'][$key];
    }
    else {
      $return[$key] = FALSE;
    }
    if ($return[$key] === 'All'  || !is_numeric($return[$key])) {
      $return[$key] = FALSE;
    }
  }
  if (!empty($return['og_group_ref_target_id_mine'])) {
    $return['og_group_ref_target_id'] = FALSE;
    $return['og_subspaces_view_all'] = FALSE;
    $return['og_subspaces_view_parent'] = FALSE;
  }
  if ($return['oa_section_ref_target_id']) {
    $return['og_subspaces_view_all'] = FALSE;
    $return['og_subspaces_view_parent'] = FALSE;
  }

  return $return;
}

/**
 * Implements hook_views_pre_view().
 */
function oa_subspaces_views_pre_view(&$view) {
  // If we are in a View where a specific group is being filtered for in an
  // exposed filter (as opposed to selecting '- Any -' or '- Active Space -').
  if (!empty($view->display_handler->default_display->options['filters']['og_group_ref_target_id']['exposed'])) {
    $settings = _oa_subspaces_find_view_settings($view);

    $og_subspaces_view_all = $settings['og_subspaces_view_all'] && oa_subspaces_get_children_groups('node', $settings['og_group_ref_target_id']);
    $og_subspaces_view_parent = $settings['og_subspaces_view_parent'] && oa_subspaces_get_parent_groups('node', $settings['og_group_ref_target_id']);

    if ($og_subspaces_view_all || $og_subspaces_view_parent) {
      // If parent or children filtering is turned on (and there are any parents
      // or children to be found), then we add a field so we can see what group
      // the content is coming from.
      $view->display_handler->default_display->options['fields'] = array(
        'og_group_ref' => array(
          'id'=> 'og_group_ref',
          'table'=> 'og_membership',
          'field'=> 'og_group_ref',
          'label'=> 'Space',
          'settings'=> array(
            'link' => 1,
          ),
        ),
      ) + $view->display_handler->default_display->options['fields'];
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function oa_subspaces_views_query_alter(&$view, &$query) {
  if (!empty($view->exposed_input['og_group_ref_target_id']) && is_numeric($view->exposed_input['og_group_ref_target_id']) && !empty($view->filter['og_group_ref_target_id']->options['exposed'])) {
    $settings = _oa_subspaces_find_view_settings($view);

    // Get all the parent or child groups if we are filtering for them.
    $extra_groups = array();
    if ($settings['og_subspaces_view_all']) {
      $extra_groups = array_merge($extra_groups, oa_subspaces_get_children_groups('node', $view->exposed_input['og_group_ref_target_id']));
    }
    if ($settings['og_subspaces_view_parent']) {
      $extra_groups = array_merge($extra_groups, oa_subspaces_get_parent_groups('node', $view->exposed_input['og_group_ref_target_id']));
    }

    // Add the extra groups to query, if there are any.
    if (!empty($extra_groups)) {
      $columns = array(
        'og_membership.gid',
        'field_data_oa_other_spaces_ref.oa_other_spaces_ref_target_id',
      );

      // Loop over all conditions in all 'where groups'.
      foreach (array_keys($query->where) as $where_group) {
        foreach ($query->where[$where_group]['conditions'] as $key => $condition) {
          // If it matches the column or an alias.
          foreach ($columns as $column) {
            if ($condition['field'] === $column ||
              (is_string($condition['field']) && substr($condition['field'], -strlen($column)-2) === "__{$column}")) {
              $query->where[$where_group]['conditions'][$key]['value'] = array_merge($query->where[$where_group]['conditions'][$key]['value'], $extra_groups);
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_field_access().
 */
function oa_subspaces_field_access($op, $field, $entity_type, $entity, $account) {
  if (!empty($field['field_name']) && $field['field_name'] == OG_USER_INHERITANCE_PERMISSION_FIELD && $op == 'edit') {
    return user_access('administer group', $account);
  }
  return TRUE;
}

/**
 * Implements hook_og_permission_alter().
 *
 * Changes group create permissions to restricted.
 */
function oa_subspaces_og_permission_alter(&$permissions) {
  foreach (node_permissions_get_configured_types() as $type) {
    if (og_is_group_type('node', $type) && ($perms = og_list_permissions($type))) {
      foreach (array_keys($perms) as $perm_name) {
        // Group permission should onyl use the global field.
        if ($type == 'oa_group') {
          unset($permissions[$perm_name]);
        }
        elseif (!empty($permissions[$perm_name])) {
          $permissions[$perm_name]['restrict access'] = TRUE;
          $permissions[$perm_name]['default role'] = array(OG_ADMINISTRATOR_ROLE);
          $permissions[$perm_name]['roles'] = array(OG_AUTHENTICATED_ROLE);
        }
      }
    }
  }
}
