<?php
/**
 * @file
 * Code for the Open Atrium Event Imports feature.
 */

include_once 'oa_events_import.features.inc';

/**
 * Implements hook_node_insert().
 */
function oa_events_import_node_presave($node) {
  if ($node->type == 'oa_event') {
    // If the feeds node was just saved Group and Space references won't
    // properly load without resetting the static cache. So we'll keep our own.
    $parents = &drupal_static(__FUNCTION__, array());

    if (!empty($node->feeds_item) && isset($node->feeds_item->feed_nid)) {

      $parent_nid = $node->feeds_item->feed_nid;
      if (!isset($parents[$parent_nid])) {
        $parent = node_load($node->feeds_item->feed_nid, NULL, TRUE);
        $parents[$parent_nid] = $parent;
      }
      else {
        $parent = $parents[$parent_nid];
      }

      drupal_alter('oa_event_create', $node, $parent);
    }
  }
}

/**
 * Implements hook_oa_event_create().
 */
function oa_events_import_oa_event_create_alter($node, $parent) {
  $node->oa_section_ref = $parent->oa_section_ref;
  $node->og_group_ref = $parent->og_group_ref;
}
