<?php

/**
 * @file
 * Provides update and install hooks for oa_config.
 */

/**
 * Implements hook_install().
 */
function oa_config_install() {
  $private_path = variable_get('file_private_path', FALSE);
  if (!$private_path) {
    $private_path = variable_get('file_public_path', conf_path() . '/files') . '/private';
    variable_set('file_private_path', $private_path);
  }
  if (!empty($private_path) && !is_dir($private_path)) {
    mkdir($private_path, 0775, TRUE);
  }
}
