<?php
/**
 * @file
 * Code for the Open Atrium Work Tracker - Due Date feature.
 */

include_once 'oa_worktracker_duedate.features.inc';

/**
 * Implements hook_views_default_views_alter().
 *
 * Temporarily do this custom, until we can track down the problem
 * in Features Override.
 *
 */
function oa_worktracker_duedate_views_default_views_alter(&$data) {
  if (isset($data['oa_worktracker'])) {
    $fields =& $data['oa_worktracker']->display['task_list']->display_options['fields'];
    $splitIndex = array_search('realname_1', array_keys($fields));
    
    $fields = array_merge(
      array_slice($fields, 0, $splitIndex),
      array('field_oa_worktracker_duedate' => array(
        'id' => 'field_oa_worktracker_duedate',
        'table' => 'field_data_field_oa_worktracker_duedate',
        'field' => 'field_oa_worktracker_duedate',
        'settings' => array(
          'format_type' => 'oa_date',
          'fromto' => 'both',
          'multiple_number' => '',
          'multiple_from' => '',
          'multiple_to' => '',
          'show_repeat_rule' => 'show',
        ),
      )),
      array_slice($fields, $splitIndex)
    );

    $data['oa_worktracker']->display['task_list']->display_options['style_options']['columns']['field_oa_worktracker_duedate'] = 'field_oa_worktracker_duedate';

    $data['oa_worktracker']->display['task_list']->display_options['style_options']['info']['field_oa_worktracker_duedate'] = array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    );
  }
}
