<?php

/**
 * @file
 * Administration navbar for quick access to top level administration items.
 */

/**
 * Implements hook_help().
 */
function navbar_help($path, $arg) {
  switch ($path) {
    case 'admin/help#navbar':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The navbar module displays links to top-level administration menu items and links from other modules at the top of the screen. For more information, see the online handbook entry for <a href="@navbar">navbar module</a>.', array('@navbar' => 'http://drupal.org/documentation/modules/navbar')) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Displaying administrative links') . '</dt>';
      $output .= '<dd>' . t('The navbar module displays a bar containing top-level administrative links across the top of the screen. Below that, the navbar module has a <em>drawer</em> section where it displays links provided by other modules, such as the core <a href="@shortcuts-help">Shortcut module</a>. The drawer can be hidden/shown by using the show/hide shortcuts link at the end of the navbar.', array('@shortcuts-help' => url('admin/help/shortcut'))) . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function navbar_permission() {
  return array(
    'access navbar' => array(
      'title' => t('Use the administration navbar'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function navbar_theme($existing, $type, $theme, $path) {
  $items['navbar'] = array(
    'render element' => 'navbar',
    'template' => 'navbar',
    'path' => drupal_get_path('module', 'navbar'),
  );
  return $items;
}

/**
 * Implements hook_page_build().
 *
 * Add admin navbar to the page_bottom region automatically.
 */
function navbar_page_build(&$page) {
  $page['page_bottom']['navbar'] = array(
    '#pre_render' => array('navbar_pre_render'),
    '#access' => user_access('access navbar'),
  );
}

/**
 * Provides pre_render function for the navbar.
 *
 * Since building the navbar takes some time, it is done just prior to
 * rendering to ensure that it is built only if it will be displayed.
 *
 * @see navbar_page_build().
 */
function navbar_pre_render($navbar) {
  $navbar = array_merge($navbar, navbar_view());
  return $navbar;
}

/**
 * Implements hook_preprocess_HOOK() for html.tpl.php.
 *
 * Add some page classes, so global page theming can adjust to the navbar.
 */
function navbar_preprocess_html(&$vars) {
  if (isset($vars['page']['page_bottom']['navbar']) && user_access('access navbar')) {
    $vars['attributes']['class'][] = 'navbar';
  }
}

/**
 * Implements hook_preprocess_HOOK() for navbar.tpl.php.
 *
 * Adding the 'overlay-displace-top' class to the navbar pushes the overlay
 * down, so it appears below the navbar.
 */
function navbar_preprocess_navbar(&$variables) {
  $variables['attributes']['class'][] = "overlay-displace-top";
}

/**
 * Implements hook_system_info_alter().
 *
 * Indicate that the 'page_bottom' region (in which the navbar will be displayed)
 * is an overlay supplemental region that should be refreshed whenever its
 * content is updated.
 *
 * This information is provided for any module that might need to use it, not
 * just the core Overlay module.
 */
function navbar_system_info_alter(&$info, $file, $type) {
  if ($type == 'theme') {
    $info['overlay_supplemental_regions'][] = 'page_bottom';
  }
}

/**
 * Builds the admin menu as a structured array ready for drupal_render().
 *
 * @return
 *   Array of links and settings relating to the admin menu.
 */
function navbar_view() {
  global $user;

  $build = array(
    '#theme' => 'navbar',
    '#attached'=> array(
      'library' => array(
        array('navbar', 'navbar.init',),
      ),
    ),
  );

  // Add logout & user account links or login link.
  if ($user->uid) {
    $links = array(
      'account' => array(
        'title' => t('Hello <strong>@username</strong>', array('@username' => format_username($user))),
        'href' => 'user',
        'html' => TRUE,
        'attributes' => array(
          'title' => t('User account'),
          'class' => array('tab'),
        ),
      ),
      'logout' => array(
        'title' => t('Log out'),
        'href' => 'user/logout',
        'attributes' => array(
          'class' => array('tab'),
        ),
      ),
    );
  }
  else {
     $links = array(
      'login' => array(
        'title' => t('Log in'),
        'href' => 'user',
        'attributes' => array(
          'class' => array('tab'),
        ),
      ),
    );
  }

  $build['navbar_user'] = array(
    '#theme' => 'links__navbar_user',
    '#links' => $links,
    '#attributes' => array(
      'id' => 'navbar-user',
      'class' => array('menu'),
    ),
    '#heading' => array('text' => t('navbar user actions'), 'level' => 'h2', 'class' => 'element-invisible'),
  );

  // Build the default navbar navigation links.
  $links = array(
    'navbar_tray_toggle' => array(
      'title' => t('Menu'),
      'href' => '',
      'html' => FALSE,
      'attributes' => array(
        'class' => array('tab', 'toggle', 'toggle-tray'),
        'role' => 'button',
      ),
    ),
    'home' => array(
      'title' => t('Home'),
      'href' => '<front>',
      'html' => FALSE,
      'attributes' => array(
        'title' => t('Home'),
        'class' => array('tab', 'home-link'),
      ),
    ),
  );

  // navbar navigation links.
  $build['navbar_navigation'] = array(
    '#theme' => 'links',
    '#links' => $links,
    '#attributes' => array(
      'id' => 'navbar-actions',
      'class' => array('menu'),
    ),
    '#heading' => array('text' => t('navbar navigation'), 'level' => 'h2', 'class' => 'element-invisible'),
  );

  // Retrieve the admin menu from the database.
  $tree = navbar_get_menu_tree();
  // Add attributes to the links before rendering.
  navbar_menu_navigation_links($tree);
  $build['navbar_menu'] = menu_tree_output($tree);

  // Shortcuts.
  $build['navbar_shortcuts'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'navbar-shortcuts',
        'clearfix',
      ),
    ),
  );

  return $build;
}

/**
 * Translate menu_local_action links to standard links for theme_links.
 *
 *
 * The function theme_menu_local_actions expects a the properties of the link to
 * be stored under a #link property. The function theme_links expects the
 * properties of the link to be direct children of the link array. So unset the
 * #theme property and move the properties under #link to the parent property of
 * #link.
 *
 * @see theme_menu_local_action
 * @see theme_links
 */
function navbar_convert_action_links_to_standard_links($links = array()) {
  foreach ($links as $key => $link) {
    unset($links[$key]['#theme']);
    foreach ($link['#link'] as $prop => $value) {
      $links[$key][$prop] = $value;
    }
    unset($links[$key]['#link']);
  }
  return $links;
}

/**
 * Gets only the top level items below the 'admin' path.
 *
 * @return
 *   An array containing a menu tree of top level items below the 'admin' path.
 */
function navbar_get_menu_tree() {
  $tree = array();
  $admin_link = db_query('SELECT * FROM {menu_links} WHERE menu_name = :menu_name AND module = :module AND link_path = :path', array(':menu_name' => 'management', ':module' => 'system', ':path' => 'admin'))->fetchAssoc();
  if ($admin_link) {
    $tree = menu_tree_all_data('management');
  }
  // Return the sub-menus of the management menu root.
  foreach ($tree as $key => $menu) {
    return (!empty($tree[$key]['below'])) ? $tree[$key]['below'] : array();
  }
  return array();
}

/**
 * Generates an array of links from a menu tree array.
 *
 * Based on menu_navigation_links(). Adds path based IDs and icon placeholders
 * to the links.
 *
 * @return
 *   An array of links as defined above.
 */
function navbar_menu_navigation_links(&$tree) {
  foreach ($tree as $key => $item) {
    // Configure sub-items.
    if (!empty($item['below'])) {
      navbar_menu_navigation_links($tree[$key]['below']);
    }
    // Make sure we have a path specific ID in place, so we can attach icons
    // and behaviors to the items.
    $tree[$key]['link']['localized_options']['attributes']['id'] = 'navbar-link-' . str_replace(array('/', '<', '>'), array('-', '', ''), $item['link']['link_path']);
  }
}

/**
 * Checks whether an item is in the active trail.
 *
 * Useful when using a menu generated by menu_tree_all_data() which does
 * not set the 'in_active_trail' flag on items.
 *
 * @return
 *   TRUE when path is in the active trail, FALSE if not.
 *
 * @todo
 *   Look at migrating to a menu system level function.
 */
function navbar_in_active_trail($path) {
  $active_paths = &drupal_static(__FUNCTION__);

  // Gather active paths.
  if (!isset($active_paths)) {
    $active_paths = array();
    $trail = menu_get_active_trail();
    foreach ($trail as $item) {
      if (!empty($item['href'])) {
        $active_paths[] = $item['href'];
      }
    }
  }
  return in_array($path, $active_paths);
}

/**
 * Implements hook_library().
 */
function navbar_library() {
  $libraries = array();
  $libraries['navbar.init'] = array(
    'title' => 'Navbar',
    'version' => VERSION,
    'js' => array(
      drupal_get_path('module', 'navbar') . '/js/navbar.js' => array(),
    ),
    'css' => array(
      drupal_get_path('module', 'navbar') . '/css/navbar.base.css',
      drupal_get_path('module', 'navbar') . '/css/navbar.theme.css',
    ),
    'dependencies' => array(
      array('system', 'jquery'),
      array('system', 'jquery.once'),
      array('system', 'jquery.cookie'),
    ),
  );

  return $libraries;
}

/**
 *
 */
/**
 * Implements hook_page_alter().
 *
 * Pull the shortcuts into the navbar.
 */
function navbar_page_alter(&$page) {
  if (module_exists('shortcut') && isset($page['page_bottom']['navbar'])) {
    // If the toolbar is available, add a pre-render function to display the
    // current shortcuts in the toolbar drawer.
    $page['page_bottom']['navbar']['#pre_render'][] = 'navbar_shortcut_pre_render';
  }
}

/**
 * Modified from shortcut_toolbar_pre_render().
 *
 * Renders user shorcut links into the navbar. 
 */
function navbar_shortcut_pre_render($navbar) {
  $links = shortcut_renderable_links();
  $links['#prefix'] = '<div class="shortcuts-list">';
  $links['#suffix'] = '</div>';
  $shortcut_set = shortcut_current_displayed_set();
  $configure_link = NULL;
  if (shortcut_set_edit_access($shortcut_set)) {
    $configure_link = array(
      '#type' => 'link',
      '#title' => t('Edit shortcuts'),
      '#href' => 'admin/config/user-interface/shortcut/' . $shortcut_set->set_name,
      '#options' => array('attributes' => array('id' => 'edit-shortcuts')),
    );
  }

  $drawer = array(
    'shortcuts' => $links,
    'configure' => $configure_link,
  );

  $navbar['navbar_shortcuts'][] = $drawer;
  return $navbar;
}
