<?php
/**
 * @file
 * Code for the oa_update module
 */

/**
 * Implements hook_menu().
 */
function oa_update_menu() {
  $items = array();
  $items['admin/reports/update_distro'] = array(
    'title' => 'Available updates',
    'description' => 'Get update information for your distribution.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oa_update_admin_form'),
    'access arguments' => array('administer site configuration'),
    'weight' => -50,
  );
  return $items;
}

/**
 * Implements hook_menu_alter
 */
function oa_update_menu_alter(&$items) {
  // swap out normal update links with our own pages
  if (!empty($items['admin/reports/updates'])) {
    $items['admin/reports/oa_updates'] = $items['admin/reports/updates'];
    $items['admin/reports/oa_updates']['type'] = MENU_CALLBACK;
    $items['admin/reports/updates'] = $items['admin/reports/update_distro'];
  }
  if (!empty($items['admin/reports/updates/update'])) {
    $items['admin/reports/oa_updates/update'] = $items['admin/reports/updates/update'];
    $items['admin/reports/oa_updates/update']['type'] = MENU_CALLBACK;
    $items['admin/reports/updates/update'] = $items['admin/reports/update_distro'];
    $items['admin/reports/updates/update']['type'] = MENU_CALLBACK;
  }
  unset($items['admin/reports/update_distro']);
}

function oa_update_admin_form() {
  $form = array();

  $form['header'] = array(
    '#theme' => 'html_tag',
    '#tag' => 'h3',
    '#value' => t('Do not manually update modules within distributions!'),
  );

  $form['help'] = array(
    '#markup' => '<p>' .
      t('Drupal Distributions contain a carefully selected set of module
      versions along with specific patches.  You should never update individual modules
      within a distribution unless you are an experience developer.')
      . '</p><p>' .
      t('If you REALLY know what you are doing, you can find the links to the normal Drupal
        update pages in the collapsed section below.')
      . '</p>',
  );

  // display the update status for just our profile
  $profile_name = drupal_get_profile();
  if (!empty($profile_name) && ($available = update_get_available(TRUE)) &&
      !empty($available[$profile_name])) {
    module_load_include('inc', 'update', 'update.compare');
    module_load_include('inc', 'update', 'update.report');
    $data = update_calculate_project_data($available);
    $profile[$profile_name] = $data[$profile_name];
    $markup = theme('update_report', array('data' => $profile));
    $markup = str_replace(
      '<h3>' . t('Modules') . '</h3>',
      '<h3>' . t('Distribution') . '</h3>', $markup);
    $form['profile'] = array(
      '#markup' => $markup,
    );
  }

  $form['update'] = array(
    '#type' => 'fieldset',
    '#title' => 'Update Links',
    '#collapsible' => TRUE,
    '#collapsed' => !variable_get('oa_update_enable', FALSE),
  );
  $form['update']['oa_update_enable'] = array(
    '#type' => 'checkbox',
    '#title' => 'Enable module update status',
    '#description' => t('Enable this option (and Save) to access the normal update links'),
    '#default_value' => variable_get('oa_update_enable', FALSE),
  );

  if (variable_get('oa_update_enable', FALSE)) {
    $links[] = array(
      'title' => 'Available updates',
      'href' => 'admin/reports/oa_updates',
    );
    $links[] = array(
      'title' => 'Check for available updates',
      'href' => 'admin/reports/oa_updates/update',
    );
    $form['update']['links'] = array(
      '#theme' => 'links',
      '#links' => $links,
    );
  }
  $form['#submit'][] = 'oa_update_admin_form_submit';
  return system_settings_form($form);
}

/**
 * Submit handler for oa_update_admin_form
 */
function oa_update_admin_form_submit($form, &$form_state) {
  if ($form_state['values']['oa_update_enable'] !== $form_state['input']['oa_update_enable']) {
    variable_set('oa_update_enable', $form_state['values']['oa_update_enable']);
    module_load_install('update');
    $status = update_requirements('runtime');
  }
}

/**
 * Implements hook_update_projects_alter().
 */
function oa_update_update_projects_alter(&$projects) {
  $profile_name = drupal_get_profile();
  if (!empty($profile_name)) {
    // add the profile back into the module list to fetch update status for
    module_load_include('inc', 'update', 'update.compare');
    $module_data = system_rebuild_module_data();
    $module[$profile_name] = $module_data[$profile_name];
    $module[$profile_name]->info['hidden'] = FALSE;
    $module[$profile_name]->info['project'] = $profile_name;
    $profile = array();
    _update_process_info_list($profile, $module, 'module', TRUE);
    // drupal.org packager doesn't add the profile version to the info file
    // can add a [version] manually to your profile.info
    // for openatrium, use the version of oa_core as the version of the profile
    if (empty($profile[$profile_name]['info']['version']) && ($profile_name == 'openatrium')) {
      $profile[$profile_name]['info']['version'] = $projects['oa_core']['info']['version'];
    }
    $projects[$profile_name] = $profile[$profile_name];
    foreach ($projects as $key => $project) {
      // remove any local OA submodules
      if (!empty($project['info']['package']) && ($project['info']['package'] == 'Open Atrium')) {
        unset($projects[$key]);
      }
    }
  }
}

/**
 * Implements hook_update_status_alter().
 */
function oa_update_update_status_alter(&$projects) {
  $profile_name = drupal_get_profile();
  foreach ($projects as $key => $project) {
    // -dev versions with patches are marked as NOT_SUPPORTED
    // but for a Distribution, these modules are Current
    if ($project['status'] == UPDATE_NOT_SUPPORTED) {
      $projects[$key]['status'] = UPDATE_CURRENT;
    }
  }
  if (!variable_get('oa_update_enable', FALSE)) {
    // we want to supress the update messages for non-security updates
    foreach ($projects as $key => $project) {
      // mark anything that isn't a security update as ok
      // don't change status of distribution version
      if (($key != $profile_name) && ($project['status'] !== UPDATE_NOT_SECURE)) {
        $projects[$key]['status'] = UPDATE_CURRENT;
      }
    }
  }
}
