<?php

/**
 * @file
 * Provides hook implementations and functionality for oa_styles.
 */

/**
 * Implements hook_ctools_plugin_directory
 */
function oa_styles_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_theme().
 */
function oa_styles_theme() {
  return array(
    'oa_styles_modal' => array(
      'template' => 'oa-styles-modal',
      'variables' => array(
        'modal_id' => 'oa-styles-modal',
        'title' => t('Default Modal Title'),
        'body' => NULL,
      ),
      'path' => drupal_get_path('module', 'oa_styles') . '/templates',
    ),
  );
}

/**
 * Implements hook_preprocess_flag().
 */
function oa_styles_preprocess_flag(&$vars) {
  $vars['flag_classes_array'][] = 'btn';
  $vars['flag_classes'] = implode(' ', $vars['flag_classes_array']);
}
