<?php
/**
 * @file
 * Code for the Open Atrium Media feature.
 */

include_once 'oa_media.features.inc';
/**
 * @file
 */

/**
 * Override theme function for Media Colorbox
 * to fix image resizing
 * copied from http://drupal.org/node/1514406
 */
function oa_media_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['media_colorbox']['function'])) {
    $theme_registry['media_colorbox']['function'] = 'oa_media_media_colorbox';
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function oa_media_field_formatter_info() {
  return array(
   'oa_media_formatter' => array(
      'label' => t('First Image'),
      'field types' => array('file'),
      'settings'  => array(
        'image_style' => 'thumbnail',
      ),
    )
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function oa_media_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  // Grab the instance settings for this view mode.
  $display = $instance['display'][$view_mode];
  // Grab configuration options for this formatter.
  $settings = $display['settings'];

  $element = array();

  if ($display['type'] == 'oa_media_formatter') {
    // Build options array.
    $styles = image_styles();
    $style_options = array();
    foreach ($styles as $style) {
      $style_options[$style['name']] = $style['name'];
    }

    $element['image_style'] = array(
      '#type' => 'select',
      '#title' => t('Image Style'),
      '#description' => t('Select the image style to use for this formatter'),
      '#default_value' => $settings['image_style'],
      '#options' => $style_options,
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_view().
 */
function oa_media_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $element = array();
  if ($display['type'] == 'oa_media_formatter') {
    foreach ($items as $delta => $item) {
      if ($item['type'] == 'image') {
        $settings = $display['settings'];
        $image = theme('image_style', array('style_name' => $settings['image_style'], 'path' => $item['uri']));

        $element[0] = array(
          '#markup' => '<div class="oa-media-first-thumbnail">' . $image . "</div>",
        );

        break;
      }
    }
  }

  return $element;
}

/**
 * Override for theme_media_colorbox.
 * We need to override the paths to support private file system access
 */
function oa_media_media_colorbox($variables) {
  $entity_id = $variables['entity_id'];
  $file_id = $variables['file_id'];
  $field = $variables['field'];
  $field_name = isset($field['field_name']) ? $field['field_name'] : '';
  $settings = $variables['display_settings'];

//switch to figure out where caption should come from
  switch ($settings['colorbox_caption']) {
    case 'title':
      $caption = $variables['title'];
      break;
    case 'mediafield':
      $caption = $variables['media_colorbox_caption'];
      break;
    default:
      $caption = '';
  }

  // Shorten the caption for the example styles or when caption shortening is active.
  $colorbox_style = variable_get('colorbox_style', 'default');
  $trim_length = variable_get('colorbox_caption_trim_length', 75);
  if ((variable_get('colorbox_caption_trim', 0)) && (drupal_strlen($caption) > $trim_length)) {
    $caption = drupal_substr($caption, 0, $trim_length - 5) . '...';
  }

  // Build the gallery id.
  switch ($settings['colorbox_gallery']) {
    case 'post':
      $gallery_id = 'gallery-' . $entity_id;
      break;
    case 'page':
      $gallery_id = 'gallery-all';
      break;
    case 'field_post':
      $gallery_id = 'gallery-' . $entity_id . '-' . $field_name;
      break;
    case 'field_page':
      $gallery_id = 'gallery-' . $field_name;
      break;
    case 'custom':
      $gallery_id = $settings['colorbox_gallery_custom'];
      break;
    default:
      $gallery_id = '';
  }

  $class = 'media-colorbox ' . $variables['item_class'];

  //load file and render for select view mode
  if ($file_id != NULL) {
    $file = file_load($file_id);
    $fview = file_view($file, $settings['file_view_mode'], $variables['langcode']);
    // override the path with the proper private file access
    if ($file->type == 'image') {
      $variables['path'] = file_create_url($file->uri);
    }
    elseif (($file->type == 'document') &&
      isset($fview['file']['#theme']) && ($fview['file']['#theme'] == 'file_entity_download_link')) {
      // don't use colorbox popup for document download links
      $variables['path'] = file_create_url($file->uri);
      $class = '';
    }
    $text = drupal_render($fview);
  }
  elseif (isset($variables['item'])) {
    $text = drupal_render($variables['item']);
  }
  //strip anchor tags as rendered output will be wrapped by another anchor tag
  //fix for issue #1477662
  $stripped_text = media_colorbox_strip_only($text, 'a');
  $output = theme('link', array(
    //'text' => drupal_render($variables['item']),
    'text' => $stripped_text,
    'path' => $variables['path'],
    'options' => array(
      'html' => TRUE,
      'attributes' => array(
        'title' => $caption,
        'class' => $class,
        'style' => $variables['item_style'],
        'rel' => $gallery_id,
        'data-mediaColorboxFixedWidth' => $settings['fixed_width'],
        'data-mediaColorboxFixedHeight' => $settings['fixed_height'],
        'data-mediaColorboxAudioPlaylist' => $settings['audio_playlist'],
      ),
    ),
  ));

  return $output;
}

/**
 * Implementation of hook_file_default_displays_alter()
 */
function oa_media_file_default_displays_alter(&$default_displays) {
  // Display the 'Generic file' display on video preview.
  if (!empty($default_displays['video__teaser__file_field_file_default'])) {
    $default_displays['video__teaser__file_field_file_default']->status = FALSE;
  }

  // Set the default video configuration for videos
  if (!empty($default_displays['video__teaser__media_vimeo_video'])) {
    $default_displays['video__teaser__media_vimeo_video']->status = FALSE;
  }

  // Set the default video configuration for videos
  if (!empty($default_displays['video__teaser__media_youtube_video'])) {
    $default_displays['video__teaser__media_youtube_video']->status = FALSE;
  }

  // Set the default image style for videos to be our custom video image style
  if (!empty($default_displays['video__teaser__media_vimeo_image'])) {
    $default_displays['video__teaser__media_vimeo_image']->settings['image_style'] = 'panopoly_image_quarter';
  }

  // Set the default image style for videos to be our custom video image style
  if (!empty($default_displays['video__teaser__media_youtube_image'])) {
    $default_displays['video__teaser__media_youtube_image']->settings['image_style'] = 'panopoly_image_quarter';
  }

  // Set the default video configuration for videos
  if (!empty($default_displays['image__teaser__file_field_image'])) {
    $default_displays['image__teaser__file_field_image']->settings['image_style'] = 'panopoly_image_quarter';
  }

}

/**
 * Implements hook_views_query_alter().
 */
function oa_media_views_query_alter(&$view, &$query) {
  $in_wysiwyg = (isset($_GET['id']) && ($_GET['id'] == 'media_wysiwyg'));
  if (($query->base_table == 'file_managed') && (!empty($view->filter['og_group_ref_target_id']->options['exposed']))) {
    // Modify file views with space filters to handle media attached to nodes and paragraphs

    // Ensure we have a relationship between og_membership and oa_media file
    if (!empty($query->table_queue['field_oa_media_file_managed__og_membership'])) {
      // Table already exists because user is probably filtering on space already
      $og_membership[] = 'field_oa_media_file_managed__og_membership';

      // This should be a left join or the results will not show for paragraphs.
      $query->table_queue['field_oa_media_file_managed__og_membership']['join']->type = "LEFT";
    }
    else {
      // If og_membership not present, then add it
      $join = new views_join();
      $join->construct('og_membership', 'field_oa_media_file_managed', 'nid', 'etid', array(
        array('field' => 'entity_type', 'value' => 'node'),
      ));
      $og_membership[] = $query->ensure_table('og_membership', 'field_oa_media_file_managed', $join);
    }

    // PART ONE: Add a relationship to check for media in oa_related fields
    if (module_exists('oa_related')) {
      // First, relate files stored in paragraph items
      $join = new views_join();
      $join->construct('field_data_field_oa_media', 'file_managed', 'fid', 'field_oa_media_fid', array(
        array('field' => 'entity_type', 'value' => 'paragraphs_item'),
        array('field' => 'deleted', 'value' => '0'),
      ));
      $paragraph = $query->add_relationship('paragraph_media', $join, 'field_data_field_oa_media', 'file_managed');

      // Next, grab the oa_related node field for those paragraphs
      $join = new views_join();
      $join->construct('field_data_field_oa_related', $paragraph, 'entity_id', 'field_oa_related_value', array(
        array('field' => 'entity_type', 'value' => 'node'),
      ));
      $related_node = $query->add_relationship('related_node', $join, 'field_data_field_oa_related', $paragraph);

      // Finally, grab the og_membership of the node associated with the oa_related field
      $join = new views_join();
      $join->construct('og_membership', $related_node, 'entity_id', 'etid', array(
        array('field' => 'entity_type', 'value' => 'node'),
      ));
      $og_membership[] = $query->ensure_table('og_membership', $related_node, $join);

      // PART TWO: Add a relationship to check for media in oa_related fields in comments
      if (module_exists('oa_comment')) {
        // First, grab the oa_related comment fields for the above paragraphs
        $join = new views_join();
        $join->construct('field_data_field_oa_related', $paragraph, 'entity_id', 'field_oa_related_value', array(
          array('field' => 'entity_type', 'value' => 'comment'),
        ));
        $related_comment = $query->add_relationship('related_comment', $join, 'field_data_field_oa_related', $paragraph);

        // Next, grab the comment associated with the oa_related field
        $join = new views_join();
        $join->construct('comment', $related_comment, 'entity_id', 'cid');
        $comment_node = $query->add_relationship('comment_node', $join, 'comment', $related_comment);

        // Finally, grab the og_membership of the node associated with the comment
        $join = new views_join();
        $join->construct('og_membership', $comment_node, 'nid', 'etid', array(
          array('field' => 'entity_type', 'value' => 'node'),
        ));
        $og_membership[] = $query->ensure_table('og_membership', $comment_node, $join);
      }
    }

    // Now update the filters for the various og_membership relationships
    if (!empty($view->exposed_raw_input['og_group_ref_target_id'])
      && is_numeric($view->exposed_raw_input['og_group_ref_target_id'])) {

      // user is filtering on group, so alter the existing where condition
      $gid = $view->exposed_raw_input['og_group_ref_target_id'];
      $group = $query->set_where_group('AND');
      foreach ($query->where[1]['conditions'] as $key => $condition) {
        // If the field is 'og_membership.gid' or an alias for the same column.
        $column = 'og_membership.gid';
        if (!empty($condition['field'])
          && is_string($condition['field'])
          && ($condition['field'] === $column
            || substr($condition['field'], -strlen($column)-2) === "__{$column}")) {

          // Move the condition to our new where group.
          // Loop through all og_membership relations
          $new_condition = db_or();
          foreach ($og_membership as $table) {
            $new_condition->condition("{$table}.gid", $gid);
          }
          $query->add_where($group, $new_condition);
          unset($query->where[1]['conditions'][$key]);
          break;
        }
      }
    }
    else if (!$in_wysiwyg) {
      // view not filtered, but ensure only media assigned to a group is shown
      $new_condition = db_or();
      // Loop through all og_membership relations
      foreach ($og_membership as $table) {
        $new_condition->condition("{$table}.gid", NULL, 'IS NOT NULL');
      }
      $group = $query->set_where_group('AND');
      $query->add_where($group, $new_condition);
    }
  }
}

