<?php
/**
 * @file
 * Code for the Open Atrium Favorites feature.
 */

include_once 'oa_favorites.features.inc';
include_once 'oa_favorites.theme.inc';

// Machine name for the favorite space flag.
define('FAVORITE_SPACE', 'favorite_space');


/*
 * Implements hook_ctools_plugin_directory
 */
function oa_favorites_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Get a user's favorited spaces.
 */
function oa_favorites_get_spaces($account = NULL) {
  global $user;
  $uid = isset($account) ? $account->uid : $user->uid;

  $items = array('ids' => array(), 'titles' => array(), 'links' => array());
  if ($flag = flag_get_flag('favorite_space')) {
    $query = db_select('node', 'n');
    $query->join('flag_content', 'f', 'n.nid = f.content_id');
    $query
      ->fields('n', array('nid', 'title'))
      ->condition('f.uid', $account->uid)
      ->condition('f.fid', $flag->fid)
      ->condition('type', 'oa_space');
    $result = $query->execute();
    while ($row = $result->fetchAssoc()) {
      $items['ids'][]    = $row['nid'];
      $items['titles'][] = check_plain($row['title']);
      $items['links'][]  = l($row['title'], 'node/' . $row['nid']);
    }
  }
  return $items;
}

/**
 * Determine whether or not a space is a user's favorite.
 *
 * @param integer $uid - User's ID.
 * @param integer $gid - Node ID of the space.
 *
 * @return boolean
 */
function oa_favorites_is_favorite_space($uid, $gid) {
  $query = db_select('flag_content', 'f')
    ->fields('f')
    ->condition('content_type', 'node')
    ->condition('content_id', $gid)
    ->condition('uid', $uid);

  $result = $query->execute()->fetch();
  return empty($result) ? FALSE : TRUE;
}


/**
 * Implements hook_preprocess_flag().
 */
function oa_favorites_preprocess_flag(&$vars) {
  if ($vars['flag']->name == 'favorite_space') {
    if ($vars['status'] == 'unflagged') {
      $vars['link_text'] = '<i class="icon-star-empty"></i> ' . $vars['link_text'];
    }
    else {
      $vars['link_text'] = '<i class="icon-star"></i> ' . $vars['link_text'];
    }
  }
}

