<?php
/**
 * @file
 * Code for the Open Atrium Notifications feature.
 */

include_once 'oa_notifications.features.inc';

/**
 * Name of session key for saving "do not notify" option
 */
define('SKIP_FLAG', 'oa_skip_notify');

/**
 * Implements hook_ctools_plugin_directory().
 */
function oa_notifications_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_menu().
 */
function oa_notifications_menu() {
  // TODO: What are the proper access conditions here.
  $items['js/oa_notifications/details/%node'] = array(
    'title' => 'Open Atrium Notification Details',
    'page callback' => 'oa_notifications_ajax_details',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_contextual_tabs_alter().
 *
 * Adds a "Subscribe" or "Unsubscribe" flag.
 */
function oa_notifications_contextual_tabs_alter(&$data) {
  if ($node = menu_get_object()) {
    drupal_add_js(drupal_get_path('module', 'oa_notifications') . '/oa_notifications.js');
    array_push($data['links'], array('data' => flag_create_link('subscribe_section_content', $node->nid)));
  }
}

/**
 * Implements hook_theme().
 */
function oa_notifications_theme() {
  return array(
    'oa_notifications_view' => array(
      'template' => 'oa-notifications-view',
      'variables' => array(
        'node' => NULL,
        'group' => array(),
        'team' => array(),
        'user' => array(),
        'subscribe' => array(),
        'show_details' => array(),
      ),
      'path' => drupal_get_path('module', 'oa_notifications') . '/templates',
    ),
    'oa_notifications_details' => array(
      'template' => 'oa-notifications-details',
      'variables' => array(
        'users' => array(),
      ),
      'path' => drupal_get_path('module', 'oa_notifications') . '/templates',
    ),
  );
}


/**
 * Return the resolved list of all users to be notified on a piece of content.
 *
 * @param object $node
 *   The node to return notifications.
 *
 * @return array
 *   An array of users keyed by uid.
 */
function oa_notifications_get_notifications($node) {
  $bucket = &drupal_static(__FUNCTION__);

  // See if notifications should be skipped.
  if (oa_notification_skip()) {
    return array();
  }

  if (!isset($bucket)) {
    $bucket = array();
    $gid = oa_core_get_space_context();
    $notifications = oa_notifications_load_multiple($node);

    if (isset($notifications['group'])) {
      foreach (array_keys($notifications['group']) as $group_id) {
        $users = oa_core_get_group_users_for_space($gid, $group_id);
        $bucket += $users;
      }
    }

    if (isset($notifications['team'])) {
      foreach (array_keys($notifications['team']) as $team_id) {
        $results = oa_teams_get_team_members($team_id);
        $users = user_load_multiple(array_keys($results));
        $bucket += $users;
      }
    }

    if (isset($notifications['user'])) {
      $users = user_load_multiple(array_keys($notifications['user']));
      $bucket += $users;
    }

    // Also grab users who flagged the content.
    $users = flag_get_content_flags('node', $node->nid, 'subscribe_section_content');
    if (!empty($users) && is_array($users)) {
      $bucket += $users;
    }

    // Get users who subscribed to entire section.
    if (isset($node->oa_section_ref[LANGUAGE_NONE][0]['target_id'])) {
      $users = flag_get_content_flags('node', $node->oa_section_ref[LANGUAGE_NONE][0]['target_id'], 'subscribe_section_content');
      if (!empty($users) && is_array($users)) {
        $bucket += $users;
      }
    }

    // Get users who subscribed to entire space.
    if (isset($node->og_group_ref[LANGUAGE_NONE][0]['target_id'])) {
      $users = flag_get_content_flags('node', $node->og_group_ref[LANGUAGE_NONE][0]['target_id'], 'subscribe_section_content');
      if (!empty($users) && is_array($users)) {
        $bucket += $users;
      }
    }

    // Allow modules to alter users.
    drupal_alter('notifications_users', $bucket, $node);
  }

  return $bucket;
}

/**
 * Some utility functions...
 */

/**
 * Gets the users for a particular node.
 *
 * Get the listing of users that are in the specified space, or the current
 * space if no space is specified that also have access to the provided node.
 *
 * @param int $gid
 *   The space ID.
 */
function oa_notifications_get_users_for_node($node, $gid = NULL) {
  if (!isset($gid)) {
    $gid = oa_core_get_space_context();
  }
  $query = db_select('users', 'u');
  $query->rightJoin('og_membership', 'og', 'u.uid = og.etid');
  $query->fields('u', array('uid', 'name'))
      ->condition('og.entity_type', 'user')
      ->condition('og.gid', $gid);

  $results = $query->execute()->fetchAllAssoc('uid');

  // @TODO: This won't scale. We need users that have access to the given node
  // which is controlled by node_access grants, etc.  Not easily queried.
  // The move to an autocomplete might make this potential performance problem
  // disappear.
  $users = user_load_multiple(array_keys($results));
  if (isset($node->nid)) {
    foreach ($users as $uid => $user) {
      if (!node_access('view', $node, $user)) {
        unset($users[$uid]);
      }
    }
  }
  return $users;
}

/**
 * Return all notifications for given source.  Optionally filtered by type.
 *
 * @param int $source_entity
 *   The loaded source entity.
 * @param string $source_type
 *   The entity type of the source (defaults to 'node').
 * @param string $target_type
 *   An optional parameter that allows to filter the notification based on
 *   target type (group, team, user).
 *
 * @return array
 *   Returns an associative array of notifications first keyed by target type,
 *   then beneath that keyed by the target_id.
 */
function oa_notifications_load_multiple($source_entity, $source_type = 'node', $target_type = NULL) {
  $source_id = current(entity_extract_ids($source_type, $source_entity));
  $query = db_select('oa_notifications', 'n')
    ->fields('n')
    ->condition('n.source_id', $source_id)
    ->condition('n.source_type', $source_type);

  if (isset($target_type)) {
    $query->condition('n.target_type', $target_type);
  }

  $notifications = array();
  $results = $query->execute()->fetchAllAssoc('notification_id');

  foreach ($results as $id => $row) {
    $notifications[$row->target_type][$row->target_id] = $row;
  }

  drupal_alter('oa_notifications_load', $notifications, $source_entity, $source_type, $target_type);

  return $notifications;
}

/**
 * Saves notifications.
 *
 * @param array $values
 *   The values to save.
 */
function oa_notifications_save_notifications($values) {
  if (isset($values['notifications']['skip_notify'])) {
    $_SESSION[SKIP_FLAG] = $values['notifications']['skip_notify'];
  }
  if (isset($values['source_entity']) && isset($values['source_type'])) {
    drupal_alter('oa_notifications_save', $values);
    $source_type = $values['source_type'];
    $source_id = current(entity_extract_ids($source_type, $values['source_entity']));
    $notifications = array();

    if (isset($values['override'])) {
      oa_notifications_save_override($source_type, $source_id, $values['override']);
    }
    if (!isset($values['override']) || $values['override']) {
      foreach (array('group', 'team', 'user') as $type) {
        foreach ($values['notifications'][$type] as $id) {
          $n = new stdClass();
          $n->source_id = $source_id;
          $n->source_type = $source_type;
          $n->target_id = $id;
          $n->target_type = $type;
          $notifications[] = $n;
        }
      }
    }

    oa_notifications_save_for_source($source_id, $source_type, $notifications);
  }
}

/**
 * Save a collection of Notifications for a particular source item.
 *
 * @param int $source_id
 *   The ID of the source (typically a nid).
 * @param string $source_type
 *   The entity type of the source (defaults to 'node').
 * @param array $notifications
 *   A collection of Notification object for this source.
 */
function oa_notifications_save_for_source($source_id, $source_type, $notifications) {
  db_delete('oa_notifications')
    ->condition('source_id', $source_id)
    ->condition('source_type', $source_type)
    ->execute();

  foreach ($notifications as $n) {
    drupal_write_record('oa_notifications', $n);
  }
}


/**
 * Implements hook_node_insert().
 */
function oa_notifications_node_insert($node) {
  if (oa_notifications_is_notification_type($node)) {
    $node->oa_notifications['source_entity'] = $node;
    oa_notifications_save_notifications($node->oa_notifications);
  }
}

/**
 * Implements hook_node_update().
 */
function oa_notifications_node_update($node) {
  if (oa_notifications_is_notification_type($node) && isset($node->oa_notifications)) {
    $node->oa_notifications['source_entity'] = $node;
    oa_notifications_save_notifications($node->oa_notifications);
  }
}

/**
 * Determine if this is an entity type which we need to provide notifications.
 *
 * @param object $node
 *   The node object.
 *
 * @return bool
 *   Returns TRUE if entity type requires providing notifications.
 */
function oa_notifications_is_notification_type($node) {
  // @TODO: Implement this as configurable. For now, add
  // notifications to any group-content type, and groups themselves.
  $types = oa_core_list_content_types(TRUE);

  // Default notifications on spaces.
  $types[OA_SPACE_TYPE] = TRUE;

  // No notifications on teams.
  unset($types[OA_TEAM_TYPE]);

  return (array_key_exists($node->type, $types));
}

/**
 * Implements hook_node_delete().
 *
 * Cleanup the notifications for teams and groups as they are removed.
 */
function oa_notifications_node_delete($node) {
  if ($node->type == OA_TEAM_TYPE) {
    $target_type = 'team';
  }
  elseif ($node->type == OA_GROUP_TYPE) {
    $target_type = 'group';
  }

  if (isset($target_type)) {
    oa_notifications_delete_for_target($node->nid, $target_type);
  }
}

/**
 * Delete notifications for a target.
 *
 * @param int $id
 *   The target id (e.g. node id).
 * @param string $type
 *   The target type (e.g. 'group', 'team').
 */
function oa_notifications_delete_for_target($id, $type) {
  db_delete('oa_notifications')
    ->condition('target_id', $id)
    ->condition('target_type', $type)
    ->execute();
}

/**
 * AJAX callback saves the quick reply notification configuration.
 */
function oa_notifications_ajax_callback($form, $form_state) {
  oa_notifications_save_notifications($form_state['values']);

  $element = $form_state['triggering_element']['#name'];
  return $form[$element];
}

/**
 * Callback for AJAX saving of the skip-notification option.
 */
function oa_notifications_skip_ajax_callback($form, $form_state) {
  if (isset($form_state['values']['notifications']['skip_notify'])) {
    $_SESSION[SKIP_FLAG] = $form_state['values']['notifications']['skip_notify'];
  }

  $element = $form_state['triggering_element']['#name'];
  return $form[$element];
}

/**
 * Define the fields that are used for configuring notifications.
 */
function oa_notifications_form_fields(&$form, &$form_state, $node) {
  $nid = isset($node->nid) ? $node->nid : 0;
  $form['source_type'] = array(
    '#type' => 'value',
    '#value' => 'node',
  );
  $form['source_entity'] = array(
    '#type' => 'value',
    '#value' => $node,
  );

  $default = array(
    'group' => array(),
    'team' => array(),
    'user' => array(),
  );

  $notifications = array();
  // Get from form state, if available, for AJAX.
  $override = isset($form_state['values']['oa_notifications']['override']) ?
    $form_state['values']['oa_notifications']['override'] :
    oa_notifications_is_overriding('node', $nid);
  // Sections are handled differently due to space inheritance and overriding.
  if ($node->type == 'oa_section') {
    $form['override'] = array(
      '#type' => 'checkbox',
      '#title' => t('Override default notifications'),
      '#default_value' => $override,
      '#ajax' => array(
        'wrapper' => 'notifications-fields',
        'callback' => 'oa_notifications_form_fields_override_ajax',
      ),
    );
    $notifications = $override ?
      oa_notifications_load_multiple($node) :
      oa_notifications_get_default_notifications(0, 0, $override);
  }
  else {
    // Space node, check for parent space in URL for defaults.
    $parent = 0;
    $dont_use_space = TRUE;

    if (!empty($_GET[OA_PARENT_SPACE]) && is_numeric($_GET[OA_PARENT_SPACE])) {
      $parent = $_GET[OA_PARENT_SPACE];
      $dont_use_space = NULL;
    }

    $override = TRUE;
    $notifications = $nid ?
      oa_notifications_load_multiple($node) :
      oa_notifications_get_default_notifications(0, $parent, $dont_use_space);
  }

  $notifications = array_merge($default, $notifications);

  $all_groups = oa_core_get_all_groups();
  $form['notifications'] = array(
    '#type' => 'markup',
    '#tree' => TRUE,
    '#prefix' => '<div id="notifications-fields">',
    '#suffix' => '</div>',
  );

  $group_options = array_map(create_function('$group', 'return $group->title;'), $all_groups);
  if (($node->type == OA_SPACE_TYPE) && (empty($node->nid))) {
    // do not add space to notification list when creating a new space
  }
  else {
    $space_id = oa_core_get_space_context();
    if (!empty($space_id) && ($space = node_load($space_id))) {
      $group_options = array($space->nid => $space->title) + $group_options;
    }
  }

  $form['notifications']['group'] = array(
    '#type' => 'select',
    '#title' => t('Groups'),
    '#multiple' => TRUE,
    '#options' => $group_options,
    '#default_value' => array_keys($notifications['group']),
    '#disabled' => !$override,
  );

  $space_teams = oa_teams_get_teams_for_space();
  $form['notifications']['team'] = array(
    '#type' => 'select',
    '#title' => t('Teams'),
    '#multiple' => TRUE,
    '#options' => array_map(create_function('$team', 'return $team->title;'), $space_teams),
    '#default_value' => array_keys($notifications['team']),
    '#disabled' => !$override,
  );

  $space_users = oa_notifications_get_users_for_node($node);
  $form['notifications']['user'] = array(
    '#type' => 'select',
    '#title' => t('Users'),
    '#multiple' => TRUE,
    '#options' => array_map(create_function('$user', 'return oa_core_realname($user);'), $space_users),
    '#default_value' => array_keys($notifications['user']),
    '#disabled' => !$override,
  );

  oa_notifications_reset();
  $form['notifications']['skip_notify'] = array(
    '#type' => 'checkbox',
    '#title' => t('Do not send notifications for this update.'),
  );

}

/**
 * AJAX callback for oa_notifications_form_fields override checkbox.
 */
function oa_notifications_form_fields_override_ajax($form, &$form_state) {
  return $form['oa_notifications']['notifications'];
}


/**
 * Implements hook_form_node_form_alter().
 */
function oa_notifications_form_node_form_alter(&$form, &$form_state, $form_id) {
  // We are on a node/edit/add form.
  // Check content type.
  if (isset($form['#node']) && (oa_notifications_is_notification_type($form['#node']))) {
    $form['oa_notifications'] = array(
      '#type' => 'fieldset',
      '#title' => t('Notifications'),
      '#collapsible' => TRUE,
      '#collapsed' => (in_array($form['#node']->type, array(OA_GROUP_TYPE, OA_SECTION_TYPE))) ? TRUE : FALSE,
      '#weight' => 9,
      '#tree' => TRUE,
    );
    oa_notifications_form_fields($form['oa_notifications'], $form_state, $form['#node']);
  }
}

/**
 * Gets a piece of section content's default notifications.
 *
 * @param int $section_id
 *   Node ID of the content's section. Optional.
 * @param int $space_id
 *   Node ID of the content's space. Optional.
 */
function oa_notifications_get_default_notifications($section_id = 0, $space_id = 0, $override = NULL) {
  $notifications = array();
  // Space / section default to what's in the context.
  $section_id = ($section_id) ? $section_id : oa_core_get_section_context();
  $space_id = ($space_id) ? $space_id : oa_core_get_space_context();

  $section = node_load($section_id);
  if ($section) {
    $override = is_null($override) ?
      oa_notifications_is_overriding('node', $section_id) :
      $override;
    if ($override) {
      $notifications = oa_notifications_load_multiple($section);
    }
    else {
      // Switch to the section's space, if available.
      $space_id = empty($section->og_group_ref) ?
        $space_id :
        $section->og_group_ref[LANGUAGE_NONE][0]['target_id'];
    }
  }

  // If the section isn't overriding notifications OR section ID wasn't set AND
  // the space ID is set, use the space's notifications instead.
  if (empty($override) && $space = node_load($space_id)) {
    $notifications = oa_notifications_load_multiple($space);
  }

  return $notifications;
}

/**
 * Return the listing of users to be notified for the provided Node.
 *
 * @param object $node
 *   The node object.
 */
function oa_notifications_ajax_details($node) {
  $bucket = oa_notifications_get_notifications($node);

  $render = array();
  foreach ($bucket as $uid => $user) {
    if (node_access('view', $node, $user)) {
      $render[$uid] = array(
        'name' => oa_core_realname($user),
        'mail' => $user->mail,
      );
    }
  }

  echo theme('oa_notifications_details', array('users' => $render));
}

/**
 * Returns whether or a node is overriding default notifications or not.
 *
 * @param string $entity_type
 *   Entity type to check
 * @param int $entity_id
 *   Entity ID to check.
 *
 * @return int
 *   Whether or not it's overriding. Default is not overriding.
 */
function oa_notifications_is_overriding($entity_type, $entity_id) {
  $override = db_select('oa_notifications_override', 'oa_no')
    ->fields('oa_no')
    ->condition('entity_type', $entity_type)
    ->condition('entity_id', $entity_id)
    ->execute()
    ->fetch();
  return $override ? $override->override : 0;
}

/**
 * Saves an entity's override settings.
 *
 * @param string $entity_type
 *   The entity type.
 * @param int $entity_id
 *   The entity id.
 * @param mixed $override
 *   Whether or not they're overriding. Bool or int.
 */
function oa_notifications_save_override($entity_type, $entity_id, $override) {
  db_merge('oa_notifications_override')
    ->key(array(
      'entity_type' => $entity_type,
      'entity_id' => $entity_id,
    ))
    ->fields(array(
      'entity_type' => $entity_type,
      'entity_id' => $entity_id,
      'override' => $override,
    ))
    ->execute();
}


/**
 * Implements hook_flag_default_flags().
 */
function oa_notifications_flag_default_flags() {
  $flags = array();
  // Exported flag: "Section Content Subscribe".
  $flags['subscribe_section_content'] = array(
    'content_type' => 'node',
    'title' => 'Section Content Subscribe',
    'global' => 0,
    'types' => array(),
    'flag_short' => 'Subscribe',
    'flag_long' => 'Subscribe to receive messages related to this content',
    'flag_message' => 'Subscribed',
    'unflag_short' => 'Unsubscribe',
    'unflag_long' => 'Unsubscribe to stop receiving messages about this content',
    'unflag_message' => 'Unsubscribed',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'roles' => array(
      'flag' => array(
        0 => 2,
      ),
      'unflag' => array(
        0 => 2,
      ),
    ),
    'weight' => 0,
    'show_on_form' => 0,
    'access_author' => '',
    'show_on_page' => 0,
    'show_on_teaser' => 0,
    'show_contextual_link' => FALSE,
    'i18n' => 0,
    'api_version' => 2,
  );
  return $flags;
}

/**
 * Implements hook_preprocess_flag().
 */
function oa_notifications_preprocess_flag(&$vars) {
  if ($vars['flag']->name == 'subscribe_section_content') {
    if ($vars['status'] == 'unflagged') {
      $vars['link_text'] = '<i class="icon-flag"></i> ' . $vars['link_text'];
    }
    else {
      $vars['link_text'] = '<i class="icon-ban-circle"></i> ' . $vars['link_text'];
    }
  }
}

/**
 * Reset any notification flag saved in session.
 */
function oa_notifications_reset() {
  if (isset($_SESSION[SKIP_FLAG])) {
    unset($_SESSION[SKIP_FLAG]);
  }
}

/**
 * Return whether notification should be skipped.
 */
function oa_notification_skip() {
  // See if session is overriding the notification option.
  if (isset($_SESSION[SKIP_FLAG])) {
    return $_SESSION[SKIP_FLAG];
  }
  return FALSE;
}
