<?php
/**
 * @file
 * oa_tour.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function oa_tour_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_bootstrap_tour_spaces'
  $field_bases['field_bootstrap_tour_spaces'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_bootstrap_tour_spaces',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-autocomplete' => array(
            'status' => 0,
          ),
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'lock_revision' => 0,
        'reference_revisions' => 0,
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'oa_space' => 'oa_space',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
